수정함:        .github/workflows/ios_build.yml

diff --git a/.github/workflows/ios_build.yml b/.github/workflows/ios_build.yml
--- a/.github/workflows/ios_build.yml
+++ b/.github/workflows/ios_build.yml
@@ -18,49 +18,38 @@ jobs:
           cache: yarn
 
       - name: Install dependencies
-        run: | 
+        run: |
           yarn install --frozen-lockfile
-          npx react-native bundle \
-          --platform ios \
-          --dev false \
-          --entry-file index.js \
-          --bundle-output ios/main.jsbundle \
-          --assets-dest ios
 
-      - name: Setup Ruby 
+      - name: Generate React Native Codegen
+        run: |
+          node node_modules/react-native/scripts/generate-codegen-artifacts.js \
+            --path . \
+            --outputPath ios/ \
+            --targetPlatform ios
+
+      - name: Bundle React Native
+        run: |
+          npx react-native bundle \
+            --platform ios \
+            --dev false \
+            --entry-file index.js \
+            --bundle-output ios/main.jsbundle \
+            --assets-dest ios
+
+      - name: Setup Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: '3.3.8'
-          bundler-cache: true   
-          
-      # 3️⃣ CocoaPods 설치
+          bundler-cache: true
+
       - name: Install CocoaPods
+        working-directory: ios
+        env:
+          NODE_BINARY: /opt/homebrew/bin/node
+          RCT_NEW_ARCH_ENABLED: '1'
         run: |
-          cd ios
-          export BUNDLE_GEMFILE=Gemfile
-          export NODE_BINARY=$(which node)
-          export RCT_NEW_ARCH_ENABLED=1
-          rm -rf Pods Podfile.lock
-          pod install --repo-update
-        #bundle exec pod install
-
-      
-      - name: Patch Local Podspecs Codegen check
-        run: |
-          PROJECT="ios/Pods/Pods.xcodeproj/project.pbxproj"
-          sed -i '' 's|Checking whether Codegen has run|echo '"'"'Codegen check skipped'"'"'|g' "$PROJECT"
-          
-          find ios/Pods/Local\ Podspecs -type f -name "*.podspec.json" -exec \
-          sed -i '' 's|Checking whether Codegen has run|echo '"'"'Codegen check skipped'"'"'|g' {} +   
-
-          grep -R "Codegen did not run properly" ios || echo "Patch applied"
-
-      # 4️⃣ Symlink 생성 (Pods Headers)
-      - name: Fix React-Codegen symlink
-        run: |
-          mkdir -p ios/Pods/Headers/Public
-          ln -sf ../../build/generated ios/Pods/Headers/Public/React-Codegen
-          echo "✅ Symlink created"
+          bundle exec pod install --repo-update
 
       - name: Import Code-Signing Certificates
         uses: Apple-Actions/import-codesign-certs@v6.0.0
@@ -74,11 +63,24 @@ jobs:
       - name: Setup provisioning profile
         run: |
           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-          echo "${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}" | base64 --decode > /tmp/profile.mobileprovision
-          UUID=$(security cms -D -i /tmp/profile.mobileprovision | plutil -extract UUID raw -)
-          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
-          chmod 644 ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
-          security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | plutil -extract Name raw -
+
+          echo "${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}" \
+            | base64 --decode \
+            > /tmp/profile.mobileprovision
+
+          UUID=$(security cms -D \
+            -i /tmp/profile.mobileprovision \
+            | plutil -extract UUID raw -)
+
+          cp /tmp/profile.mobileprovision \
+            ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
+
+          chmod 644 \
+            ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
+
+          security cms -D \
+            -i ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision \
+            | plutil -extract Name raw -
 
       - name: Create exportOptions.plist
         run: |
@@ -89,19 +91,22 @@ jobs:
           <dict>
             <key>method</key>
             <string>app-store-connect</string>
+
             <key>signingStyle</key>
             <string>manual</string>
+
             <key>provisioningProfiles</key>
             <dict>
-            <key>kr.co.humake</key>
-            <string>humake_production</string>
+              <key>kr.co.humake</key>
+              <string>humake_production</string>
             </dict>
-            <key>compileBitcode</key>
-            <true/>
+
             <key>destination</key>
             <string>export</string>
+
             <key>stripSwiftSymbols</key>
             <true/>
+
             <key>thinning</key>
             <string>none</string>
           </dict>
@@ -110,12 +115,12 @@ jobs:
 
       - name: Validate exportOptions.plist
         run: |
-          plutil -lint ios/exportOptions.plist            
+          plutil -lint ios/exportOptions.plist
 
-      # 6️⃣ Build
       - name: Build archive
         run: |
           set -o pipefail
+
           xcodebuild \
             -workspace ios/humake.xcworkspace \
             -scheme humake \
@@ -127,21 +132,31 @@ jobs:
             PROVISIONING_PROFILE=5fb10f42-9454-4eb8-9c41-11ff94617b2f \
             CODE_SIGN_IDENTITY="iPhone Distribution" \
             archive \
-            -verbose | tee xcodebuild.log
+            -verbose \
+            | tee xcodebuild.log
 
       - name: Extract errors
         if: always()
         run: |
-          grep -E "error:|fatal error|CodeSign|Provisioning|No Accounts" xcodebuild.log || true
-          grep -n "clang: error" -B 20 -A 20 xcodebuild.log  || true
-          
+          echo "===== ERRORS ====="
+          grep -E \
+            "error:|fatal error|CodeSign|Provisioning|No Accounts" \
+            xcodebuild.log || true
+
+          echo "===== CLANG ERRORS ====="
+          grep -n \
+            "clang: error" \
+            -B 20 \
+            -A 20 \
+            xcodebuild.log || true
+
       - name: Export IPA
         run: |
           xcodebuild -exportArchive \
-          -archivePath build/humake.xcarchive \
-          -exportPath build \
-          -exportOptionsPlist ios/exportOptions.plist \
-          -allowProvisioningUpdates
+            -archivePath build/humake.xcarchive \
+            -exportPath build \
+            -exportOptionsPlist ios/exportOptions.plist \
+            -allowProvisioningUpdates
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
@@ -151,13 +166,16 @@ jobs:
 
       - name: Install gems (fastlane)
         working-directory: ./ios/fastlane
-        run: bundle install --jobs 4 --retry 3          
-          
-      - name: Decode App Store Connect API Key
-        working-directory: ./ios      
         run: |
-          echo "${{ secrets.APPLE_API_KEY_P8 }}" | base64 --decode > ./fastlane/AuthKey.p8
-          
+          bundle install --jobs 4 --retry 3
+
+      - name: Decode App Store Connect API Key
+        working-directory: ./ios
+        run: |
+          echo "${{ secrets.APPLE_API_KEY_P8 }}" \
+            | base64 --decode \
+            > ./fastlane/AuthKey.p8
+
       - name: Upload IPA to TestFlight
         working-directory: ./ios/fastlane
         run: bundle exec fastlane upload_ipa
